config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :days

  authenticated :user do
    root 'days#intro', as: "authenticated_root"
  end

  root 'welcome#index'

  get 'static_pages/results'
  get 'static_pages/goals'

end

app/models/day.rb
class Day < ActiveRecord::Base
  belongs_to :user

  def meditation_result
    if meditation_actual.blank? || meditation_actual == 0
      " No actuals yet"
    elsif meditation.blank? || meditation == 0
      " No goals set"
    else
      result = (meditation - meditation_actual)
      status = "Competed"
      extra = (meditation_actual - meditation)

      if result > 0
        result.to_s + " Left"
      elsif result == 0
        status
      else
        extra.to_s + " Extra!"
      end
    end
  end

  def push_up_result
    if actual_push_ups.blank? || actual_push_ups == 0
      " No actuals yet"
    elsif meditation.blank? || meditation == 0
      " No goals set"
    else
      result = (push_up - actual_push_ups)
      status = "Competed"
      extra = ( actual_push_ups - push_up )

      if result > 0
        result.to_s + " Left"
      elsif result == 0
        status
      else
        extra.to_s + " Extra! Champ!!"
      end
    end
  end

  def abcrunch_result
    if abcrunch_actual.blank? || abcrunch_actual == 0
      " No actuals yet"
    elsif meditation.blank? || meditation == 0
      " No goals set"
    else
      result = (abdominal_crunch - abcrunch_actual)
      status = "Competed"
      extra = (abcrunch_actual - abdominal_crunch)

      if result > 0
        result.to_s + " Left"
      elsif result == 0
        status
      else
        extra.to_s + " Extra!"
      end
    end
  end

  def scissors_result
    if leg_scissors_actual.blank? || leg_scissors_actual == 0
      " No actuals yet"
    elsif meditation.blank? || meditation == 0
      " No goals set"
    else
      result = (leg_Scissors - leg_scissors_actual)
      status = "Competed"
      extra = (leg_scissors_actual - leg_Scissors)

      if result > 0
        result.to_s + " Left"
      elsif result == 0
        status
      else
        extra.to_s + " Extra!"
      end
    end
  end

  def walk_run_result
    if walk_run_actual.blank? || walk_run_actual == 0
      " No actuals yet"
    elsif meditation.blank? || meditation == 0
      " No goals set"
    else
      result = (walk_run - walk_run_actual)
      status = "Competed"
      extra = (walk_run_actual - walk_run)

      if result > 0
        result.to_s + " Left"
      elsif result == 0
        status
      else
        extra.to_s + " Extra!"
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :days
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :authenticate_user!
  before_action :find_day, only: [:show, :edit, :update, :destroy]
  before_action :day_user?, only: [:show]

  def index
    @days = Day.where(user_id: current_user).order("created_at DESC")
  end

  def show
  end

  def new
    @day = current_user.days.build
  end

  def create
    @day = current_user.days.build(day_params)

    if @day.save
      redirect_to @day
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @day.update(day_params)
      redirect_to @day
    else
      render "edit"
    end
  end

  def destroy
    @day.destroy
    redirect_to root_path
  end

  private

    def find_day
      @day = Day.find(params[:id])
    end

    def day_user?
      redirect_to root_path, notice: "You are not authorized for this page" unless @day.user_id == current_user.id
    end

    def authenticate_user!
      redirect_to new_user_session_path, notice: "You must login or signup first" unless user_signed_in?
    end

    def day_params
      params.require(:day).permit(
      :inspiration, :challenge, :date, :push_up, :abdominal_crunch,
      :leg_Scissors, :kg, :meditation, :insight, :walk_run, :actual_push_ups,
      :meditation_actual, :abcrunch_actual, :leg_scissors_actual, :walk_run_actual,
      :image_name)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def results
    @day = Day.last
  end

  def goals
    @day = Day.last
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper

  def image_for_index(day)
    if day.image_name.blank?
      image_tag("default.png", class: "image_tag_listing")
    else
      image_tag(day.image_name, class: "image_tag_listing")
    end
  end

  def current_day?
    @day = Day.where(user_id: current_user)
    if @day.blank?
      false
    else
      @day.last[:date] == Date.today
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/days/_actuals_form.html.haml
Numbers only
%br/
%br/
= simple_form_for @day do |f|
  = f.input :meditation_actual, label: "Meditation in minutes", input_html: { class: "form-control"}
  = f.input :actual_push_ups, label: "Push ups", input_html: { class: "form-control"}
  = f.input :abcrunch_actual, label: "Abdominal crunches", input_html: { class: "form-control"}
  = f.input :leg_scissors_actual, label: "Leg scissors", input_html: { class: "form-control"}
  = f.input :walk_run_actual, label: "Walking or running in minutes", input_html: { class: "form-control"}
  = link_to "Back", day_path(@day), class: "btn btn-primary"
  = f.button :submit

app/views/days/_form.html.haml
= simple_form_for @day do |f|
  = f.input :date, :as => :hidden, :input_html => { :value => Date.today}
  = f.input :challenge, label: "My Challenge For Today", input_html: { class: "form-control"}
  = f.input :inspiration, label: "My Inspiration For Today", input_html: { class: "form-control"}
  = f.input :image_name, label: "Inspirational picture | url only", placeholder: "add url of picture", input_html: { class: "form-control"}
  = f.input :kg, required: false, value: number_with_precision(f.object.kg, precision: 2), label: "Kg", placeholder: "e.g. 80,2"
  = f.button :submit, class: "btn btn-secondary"
  - if !@days.blank? && Day.last[:date] == Date.today
    = link_to "Back", day_path, class: "btn btn-primary"
  - else
    = link_to "Back", root_path, class: "btn btn-primary"
  %br/

app/views/days/_goals.html.haml
= simple_form_for @day do |f|
  = f.input :meditation, label: "Meditation in minutes", hint: 'In minutes', input_html: { class: "form-control"}
  = f.input :push_up, label: "Push ups", input_html: { class: "form-control"}
  = f.input :abdominal_crunch, label: "Abdominal crunches", input_html: { class: "form-control"}
  = f.input :leg_Scissors, label: "Leg scissors", input_html: { class: "form-control"}
  = f.input :walk_run, label: "Walking or running in minutes", input_html: { class: "form-control"}
  = link_to "Back", day_path(@day), class: "btn btn-primary"
  = f.button :submit

app/views/days/_show.html.haml
%h3 Day Challenge
%h5
  = "'" + Day.last.challenge + "'"
%h3 Day Quote
%h5
  = "'" + Day.last.inspiration + "'"

app/views/days/edit.html.haml
- if !Day.last[:date].blank?
  .container
    .col-md-8.col-md-offset-2
      .row
        .panel.panel-default
          .panel-heading
            %h2 Edit Your Day
            -# %p= @day.created_at.strftime("%A %d %B %Y")
            %br/
            = render 'form'

app/views/days/index.html.haml
#posts
  - @days.each do |day|
    .post
      .post_image
        = image_for_index(day)
        -# %p= day.challenge
      .post_content
        .title
          %h2= link_to day.created_at.strftime("%A %e %B %Y"), day
        .data.clearfix
          %p.username
            Created by
            = day.user.name
        -#   %p.buttons
        -#     %span
        -#       %i.fa.fa-comments-o
        -#       = pluralize(post.comments.count, "comment")
        -#     %span
        -#       %i.fa.fa-thumbs-o-up
        -#       = pluralize(post.get_upvotes.size, "like")

app/views/days/intro.html.haml
- if current_day?
  #intro<
    Good
    - if Time.now.hour < 12
      morning,
    - elsif Time.now.hour < 18
      afternoon,
    - else
      evening,
    = current_user.name.capitalize
    \.
    %br/
    %h4
      = render 'days/show'
    %span#button-intro
      = link_to "Enter Your Day", day_path(Day.last)
- else
  #intro<
    Good
    - if Time.now.hour < 12
      morning,
    - elsif Time.now.hour < 18
      afternoon,
    - else
      evening,
    = current_user.name.capitalize
    \.
    %br/
    %span#button-intro
      = link_to "Create Your Day", new_day_path

app/views/days/new.html.haml
.container.col-md-offset-2
  .panel.panel-default
    .panel-heading
      %h2 Create A New Day
      %br/
      %h4= Date.today.strftime("%A %e %B %Y")
      %br/
      = render 'form'

app/views/days/show.html.haml
.container-fluid
  .day-goals
    %h2
      =@day.date.strftime("%A %B %e")
    %h4
      = "Day Challenge - " + @day.challenge
      %br/
      = "Inspiration Quote - " + @day.inspiration
      %br/
      - if @day.kg.blank?

      - else
        = "Weigth - " + "#{@day.kg.round(2)}" + " Kg"
    %br/

.day-elements
  %nav
    %ul
      %li.menu
        %h3 Goals
        %ul.list-items
          %li= "Meditation min.: " + @day.meditation.to_s
          %li= "Push ups: " + @day.push_up.to_s
          %li= "Ab Crunches: " + @day.abdominal_crunch.to_s
          %li= "Leg Scissors: " + @day.leg_Scissors.to_s
          %li= "Walk or run min.: " + @day.walk_run.to_s
          %li
            %span#button-show
              = link_to "Set Goals", static_pages_goals_path
      %li.menu
        %h3 Evaluations
        %ul.list-items
          %li= "" + @day.meditation.to_s + " - " + @day.meditation_actual.to_s + " = " + @day.meditation_result.to_s
          %li= "" + @day.push_up.to_s + " - " + @day.actual_push_ups.to_s + " = " + @day.push_up_result.to_s
          %li= "" + @day.abdominal_crunch.to_s + " - " + @day.abcrunch_actual.to_s + " = " + @day.abcrunch_result.to_s
          %li= "" + @day.leg_Scissors.to_s + " - " + @day.leg_scissors_actual.to_s + " = " + @day.scissors_result.to_s
          %li= "" + @day.walk_run.to_s + " - " + @day.walk_run_actual.to_s + " = " + @day.walk_run_result.to_s
          %li
            %span#button-show
              = link_to "Add Results", static_pages_results_path
  -# %h4
  -# - if @day.actual_push_ups.blank?
  -#   Push up: No actuals yet
  -# - else
  -# %p= "Abdominal Crunches- " + @day.abdominal_crunch.to_s + " Times"
  -# %p= "Insight- " + @day.insight.to_s

  -# .day-actuals
  #update_delete<
    %span#button-updel
      = link_to "Update", edit_day_path(@day)
    or
    %span#button-updel
      = link_to "Delete", day_path(@day), method: :delete, data: { confirm: "Are you sure?" }
    Day

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title DayApp | Online Social Diary Application
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	- if !user_signed_in?
		= yield
	- else
		%header
			.header_inner
				= link_to "MyDay", root_path, id: "logo"
				#time= Time.now.strftime("%a %b %e '%y")
				%nav
					= link_to "Overview", days_path
					= link_to "Account", edit_user_registration_path
					= link_to "Sign Out", destroy_user_session_path, method: :delete

			- flash.each do |name, msg|
				= content_tag :div, msg, class: "alert alert-info"
		= yield

app/views/static_pages/goals.html.haml
.container.col-md-offset-2
  .panel.panel-default
    .panel-heading
      %h2 Set Goals
      %br/
      %h4= Date.today.strftime("%A %e %B %Y")
      %br/
      = render 'days/goals'

app/views/static_pages/results.html.haml
.container.col-md-offset-2
  .panel.panel-default
    .panel-heading
      %h2 Set Achievements
      %br/
      %h4= Date.today.strftime("%A %e %B %Y")
      %br/
      = render 'days/actuals_form'

app/views/welcome/index.html.haml
.welcome
	#banner
		.banner_content
			= link_to "Log In", new_user_session_path
			%h1 MyDay
			%p Your online diary. Never forget an idea again.
			%button= link_to "Sign Up", new_user_registration_path
	#testimonial
		.wrapper
			%p.quote "The greatest online diary there is. Period."
			%p.name - Jorge Oosthoek. Creator of My Day.
	#callouts
		.callout_inner
			.wrapper
				.callout
					%h2 Notes
					%p Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.

				.callout
					%h2 Notes
					%p Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.

				.callout
					%h2 Notes
					%p Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.
	#bottom_cta
		.wrapper
			%h2 For Realz!
			%p I want you to sign up... If you don’t. I will find you!
			%button= link_to "Click Meee!!!", new_user_registration_path

	%footer
		%p &copy; Day App